# Generated by Django 5.1.7 on 2025-03-13 02:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("trade_code", models.CharField(max_length=20)),
                ("high", models.FloatField()),
                ("low", models.FloatField()),
                ("open", models.FloatField()),
                ("close", models.FloatField()),
                ("volume", models.IntegerField()),
            ],
        ),
    ]
